[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[languge]]
name = "python"
language-servers = ["pyright"]

# [language-server.pylsp.config.pylsp]
# plugins.pyls_mypy.enabled = true
# plugins.pyls_mypy.live_mode = true
